version: "3.9"
services:
  POSTGRES_DB:
    container_name: container-name_db
    image: postgres:11.13-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: abduvakhob.shamsiev@gmail.com
      #PGADMIN_DEFAULT_PASSWORD: a1128f69-e6f7-4e93-a2df-3d4db6030abc
    ports:
    - "80:80"
    depends_on:
      - POSTGRES_DB
volumes:
  postgres_data:
